export const ROOMS_DATA = [
  {
    id: "room-1",
    name: "Deluxe Room",
    category: "Deluxe",
    rating: 4.5,
    reviews: 128,
    size: "35 M2",
    capacity: "2 Adults",
    bed: "1 King Bed",
    price: 2500,
    discount: 0,
    image: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?q=80&w=2070&auto=format&fit=crop",
    amenities: ["Free WiFi", "AC", "TV", "Room Service"],
    desc: "An intimate sanctuary of modern elegance. Designed with subtle golden tones and plush furnishings, offering a serene escape.",
  },
  {
    id: "room-2",
    name: "Premium Room",
    category: "Premium",
    rating: 4.7,
    reviews: 95,
    size: "45 M2",
    capacity: "2 Adults",
    bed: "1 King Bed",
    price: 3500,
    discount: 10,
    image: "https://images.unsplash.com/photo-1590490360182-c33d57733427?q=80&w=1974&auto=format&fit=crop",
    amenities: ["Free WiFi", "AC", "TV", "Mini Bar", "City View"],
    desc: "Expansive luxury bathed in natural light. Featuring a grand bed, bespoke artwork, and a lavish soaking tub for ultimate relaxation.",
  },
  {
    id: "room-3",
    name: "Executive Room",
    category: "Executive",
    rating: 4.6,
    reviews: 82,
    size: "50 M2",
    capacity: "2 Adults",
    bed: "1 King Bed",
    price: 4500,
    discount: 0,
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=2070&auto=format&fit=crop",
    amenities: ["Free WiFi", "AC", "TV", "Work Desk", "Lounge Access"],
    desc: "Tailored for the modern business traveler. Offers a spacious work area, premium comfort, and exclusive access to the executive lounge.",
  },
  {
    id: "room-4",
    name: "Executive Deluxe Room",
    category: "Executive",
    rating: 4.8,
    reviews: 64,
    size: "55 M2",
    capacity: "2 Adults, 1 Child",
    bed: "1 King Bed",
    price: 5000,
    discount: 15,
    image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?q=80&w=2070&auto=format&fit=crop",
    amenities: ["Free WiFi", "AC", "Large TV", "Mini Bar", "Bathtub"],
    desc: "A harmonious blend of business and leisure amenities, ensuring every moment of your stay is both productive and refreshing.",
  },
  {
    id: "room-5",
    name: "Family Room",
    category: "Family",
    rating: 4.6,
    reviews: 145,
    size: "60 M2",
    capacity: "4 Guests",
    bed: "2 Queen Beds",
    price: 5500,
    discount: 0,
    image: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?q=80&w=1974&auto=format&fit=crop",
    amenities: ["Free WiFi", "AC", "TV", "Kids Play Area"],
    desc: "Spacious and accommodating. Designed keeping families in mind to provide ample room for relaxation and togetherness.",
  },
  {
    id: "room-6",
    name: "Family Suite",
    category: "Suite",
    rating: 4.9,
    reviews: 210,
    size: "80 M2",
    capacity: "4 Guests",
    bed: "1 King, 2 Twins",
    price: 7500,
    discount: 20,
    image: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?q=80&w=2070&auto=format&fit=crop",
    amenities: ["Free WiFi", "AC", "Living Area", "2 Bathrooms"],
    desc: "A sprawling residence offering unparalleled privacy. Features separate living quarters and majestic views for the perfect family getaway.",
  },
  {
    id: "room-7",
    name: "Luxury Suite",
    category: "Suite",
    rating: 5.0,
    reviews: 88,
    size: "95 M2",
    capacity: "2 Adults",
    bed: "1 King Bed",
    price: 9000,
    discount: 0,
    image: "https://images.unsplash.com/photo-1544148103-0773bf10d330?q=80&w=2070&auto=format&fit=crop",
    amenities: ["Free WiFi", "AC", "Jacuzzi", "Butler Service", "City View"],
    desc: "The epitome of indulgence. Immerse yourself in exquisite design, panoramic views, and personalized services tailored just for you.",
  },
  {
    id: "room-8",
    name: "Royal Suite",
    category: "Suite",
    rating: 4.9,
    reviews: 56,
    size: "120 M2",
    capacity: "3 Guests",
    bed: "1 King Bed",
    price: 12000,
    discount: 0,
    image: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?q=80&w=2070&auto=format&fit=crop",
    amenities: ["Free WiFi", "AC", "Dining Area", "Balcony", "Butler Service"],
    desc: "Live like royalty in this magnificent suite. Featuring regal decor, expansive living areas, and a private balcony overseeing the city.",
  },
  {
    id: "room-9",
    name: "Honeymoon Suite",
    category: "Romantic",
    rating: 5.0,
    reviews: 142,
    size: "85 M2",
    capacity: "2 Adults",
    bed: "1 Round King Bed",
    price: 8500,
    discount: 10,
    image: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?q=80&w=2070&auto=format&fit=crop",
    amenities: ["Free WiFi", "AC", "Jacuzzi", "Romantic Setup", "Champagne"],
    desc: "A passionate retreat designed for romance. Featuring ambient lighting, a plush bed, and a couple's jacuzzi to celebrate your love.",
  },
  {
    id: "room-10",
    name: "Presidential Suite",
    category: "Suite",
    rating: 5.0,
    reviews: 24,
    size: "180 M2",
    capacity: "4 Guests",
    bed: "2 King Beds",
    price: 25000,
    discount: 0,
    image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?q=80&w=2070&auto=format&fit=crop",
    amenities: ["Free WiFi", "AC", "Private Pool", "Kitchen", "Butler Service"],
    desc: "The pinnacle of our offerings. An unmatched luxury experience with private amenities, sweeping views, and absolute exclusivity.",
  },
  {
    id: "room-11",
    name: "Garden View Room",
    category: "Premium",
    rating: 4.4,
    reviews: 76,
    size: "40 M2",
    capacity: "2 Adults",
    bed: "1 King Bed",
    price: 3200,
    discount: 0,
    image: "https://images.unsplash.com/photo-1522771731535-61aa4459eb58?q=80&w=2070&auto=format&fit=crop",
    amenities: ["Free WiFi", "AC", "Balcony", "Garden View"],
    desc: "Wake up to serene greens. This room offers a private balcony overlooking our lush gardens, bringing nature to your doorstep.",
  },
  {
    id: "room-12",
    name: "City View Room",
    category: "Premium",
    rating: 4.5,
    reviews: 92,
    size: "40 M2",
    capacity: "2 Adults",
    bed: "1 King Bed",
    price: 3200,
    discount: 0,
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?q=80&w=2070&auto=format&fit=crop",
    amenities: ["Free WiFi", "AC", "Large Windows", "City View"],
    desc: "Experience the vibrant heartbeat of the city. Floor-to-ceiling windows provide a captivating backdrop to your luxurious stay.",
  },
  {
    id: "room-13",
    name: "Premium King Room",
    category: "Premium",
    rating: 4.8,
    reviews: 115,
    size: "48 M2",
    capacity: "2 Adults",
    bed: "1 King Bed",
    price: 4000,
    discount: 15,
    image: "https://images.unsplash.com/photo-1583847268964-b28ce8f40e02?q=80&w=2066&auto=format&fit=crop",
    amenities: ["Free WiFi", "AC", "Smart TV", "Mini Bar", "Work Desk"],
    desc: "Upgraded comfort with expansive space. Ideal for travelers seeking an extra touch of sophistication and room to unwind.",
  },
  {
    id: "room-14",
    name: "Twin Deluxe Room",
    category: "Deluxe",
    rating: 4.3,
    reviews: 67,
    size: "38 M2",
    capacity: "2 Adults",
    bed: "2 Twin Beds",
    price: 2600,
    discount: 0,
    image: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?q=80&w=2070&auto=format&fit=crop",
    amenities: ["Free WiFi", "AC", "TV", "Tea/Coffee Maker"],
    desc: "Perfect for friends or colleagues. Enjoy separate beds without compromising on the signature luxury and styling of our hotel.",
  },
  {
    id: "room-15",
    name: "Business Suite",
    category: "Executive",
    rating: 4.7,
    reviews: 89,
    size: "65 M2",
    capacity: "2 Adults",
    bed: "1 King Bed",
    price: 5800,
    discount: 0,
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=2075&auto=format&fit=crop",
    amenities: ["Free WiFi", "AC", "Meeting Area", "Printer", "Lounge Access"],
    desc: "Seamlessly blends work and rest. Features an integrated meeting space, top-tier connectivity, and classic premium comfort.",
  },
  {
    id: "room-16",
    name: "Heritage Suite",
    category: "Suite",
    rating: 4.9,
    reviews: 45,
    size: "100 M2",
    capacity: "2 Guests",
    bed: "1 Antique King Bed",
    price: 10500,
    discount: 10,
    image: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?q=80&w=1974&auto=format&fit=crop",
    amenities: ["Free WiFi", "AC", "Classic Decor", "Bathtub", "Butler Service"],
    desc: "Step back in time with vintage charm and modern luxury. Distinctive architectural details and curated antiques await you.",
  },
  {
    id: "room-17",
    name: "Luxury Family Suite",
    category: "Family",
    rating: 4.8,
    reviews: 134,
    size: "110 M2",
    capacity: "5 Guests",
    bed: "2 King Beds",
    price: 8800,
    discount: 0,
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=2070&auto=format&fit=crop",
    amenities: ["Free WiFi", "AC", "Kitchenette", "2 Bathrooms"],
    desc: "A majestic space designed for larger families. Offers a kitchenette and expansive lounge area for creating family memories.",
  },
  {
    id: "room-18",
    name: "Grand Royal Suite",
    category: "Suite",
    rating: 5.0,
    reviews: 32,
    size: "150 M2",
    capacity: "4 Guests",
    bed: "2 King Beds",
    price: 18000,
    discount: 0,
    image: "https://images.unsplash.com/photo-1598928506311-c55dd58024af?q=80&w=2070&auto=format&fit=crop",
    amenities: ["Free WiFi", "AC", "Piano", "Private Terrace", "Butler Service"],
    desc: "Grandeur beyond imagination. Revel in expansive spaces, a grand piano, and a private terrace for an opulent lifestyle experience.",
  },
  {
    id: "room-19",
    name: "Elite Executive Suite",
    category: "Executive",
    rating: 4.6,
    reviews: 55,
    size: "75 M2",
    capacity: "2 Guests",
    bed: "1 King Bed",
    price: 6500,
    discount: 5,
    image: "https://images.unsplash.com/photo-1502005097973-6a7082348e28?q=80&w=1974&auto=format&fit=crop",
    amenities: ["Free WiFi", "AC", "Boardroom", "Espresso Machine", "Lounge Access"],
    desc: "For the discerning executive. Includes a small private boardroom setup and premium espresso machine for high-stakes productivity.",
  },
  {
    id: "room-20",
    name: "Maharaja Suite",
    category: "Suite",
    rating: 5.0,
    reviews: 18,
    size: "200 M2",
    capacity: "4 Guests",
    bed: "2 King Beds",
    price: 35000,
    discount: 0,
    image: "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?q=80&w=2070&auto=format&fit=crop",
    amenities: ["Free WiFi", "AC", "Private Courtyard", "Chef on Call", "24/7 Butler"],
    desc: "An emperor's retreat. The definitive Amar Ashiyana experience featuring a private courtyard, personal chef, and lavish Indian decor.",
  }
];
